### ISSUE TITLE
Unable to save ships to disk, I get a "Network- Failed" message.

### ISSUE THREAD

**Issue by ratfeast** [Raylehnhoff/SCFSD#56] opened 2016-12-21 17:28 UTC
Unable to save ship[s to disk, I get a "Network- Failed" message after I indicate where I wish to save it. That's on google Chrome.  Internet explorer does nothing.

**Comment by Raylehnhoff** [comment] 2017-12-16 21:07
I'm unable to reproduce this on stock Chrome with no plugins. I'm assuming if it's still an issue that it's related to browser plugins.

Closing as cannot reproduce/won't fix.

**Closed as completed** 2017-12-16 21:08 UTC
Labels: wontfix, Cannot Reproduce
