### ISSUE TITLE
Download as image bug

### ISSUE THREAD

**Issue by senNish** [Raylehnhoff/SCFSD#12] opened 2015-10-11 01:07 UTC
Clicking download as image saves an image with only the background showing.

**Comment by Raylehnhoff** [comment] 2015-10-11 01:10
Please add additional information, such as browser and inputs used.

**Comment by Mccluvinn** [comment] 2015-10-16 03:17
i'm having the same issue, it happens on all browsers i tried (Firefox, Chrome, and Edge) i ended up just doing from my phone and transferring it to my computer. Not sure what it could be.....

**Comment by Raylehnhoff** [comment] 2015-10-16 03:45
This bug seems to be caused by HTTPs anywhere. I committed some code today that - I think - should resolve it. If you find that this is still an issue, please let me know.

**Comment by Raylehnhoff** [comment] 2015-10-20 18:38
Seeing no further activity on this issue, I'm going to close it.

**Closed by Raylehnhoff** 2015-10-20 18:38 UTC
